const EMOJI_ICON_MAP: Record<string, string> = {
  '🧩': 'how-it-works',
  '💳': 'credit-card',
  '✨': 'sparkles',
  '⌛': 'clock',
  '🎁': 'gift',
  '💜': 'heart',
  '🤝': 'handshake',
  '🔄': 'refresh',
  '🛍️': 'shop',
  '🧸': 'toy',
  '🧠': 'brain',
  '🧱': 'blocks',
  '🎵': 'music',
  '🎭': 'masks',
  '🎨': 'palette',
  '🌳': 'tree',
  '🌿': 'leaf',
  '💬': 'message',
  '📞': 'phone',
  '✉️': 'mail',
  '📍': 'map-pin',
  '🕒': 'clock',
  '🚗': 'car',
  '👤': 'user',
  '📦': 'package',
  '👶': 'baby',
  '⏱️': 'timer',
  '🚚': 'truck',
  '🔍': 'search',
  '⚠️': 'alert',
  '❄️': 'snowflake',
  '📅': 'calendar',
  '🎉': 'party',
  '⚡': 'bolt',
  '📋': 'copy',
  '🔗': 'link',
  '🎫': 'ticket',
  '🎯': 'pin',
  '🎀': 'gift',
  '💌': 'mail',
  '🌲': 'tree',
  '🏖': 'calendar',
  '🤒': 'heart',
  '💰': 'credit-card',
  '✈️': 'pin',
  '🛡️': 'shield',
  '🎠': 'toy',
  '🎂': 'party',
  '🎟️': 'ticket',
  '🧼': 'sparkles',
  '⚙️': 'settings',
  '📌': 'pin',
  '✅': 'check',
  '❌': 'alert',
}

const EMOJI_RE = /[\u{1F300}-\u{1FAFF}\u2600-\u27BF]/u

export function resolveIcon(value?: string | null, fallback = 'toy'): string {
  if (!value) return fallback
  if (EMOJI_ICON_MAP[value]) return EMOJI_ICON_MAP[value]
  if (!EMOJI_RE.test(value)) return value
  return fallback
}
